name: vtparse
description: A pure dart library for generating virtual terminal events from a stream of bytes
version: 1.0.0
repository: https://github.com/natebot13/dart-vtparse

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  statemachine: ^3.1.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
